{% set name = "jenkinsapi" %}
{% set version = "0.3.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1be5a3d60bb97b8fd5a9d9d4477e2201e07e4725a7d42c0eb16846bb879e4b97
  patches:
    - patches/0001-Fix-console-scripts-in-pyproject.toml.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --no-cache-dir
  missing_dso_whitelist:   # [win]
    - '*\SHLWAPI.dll'     # [win]

requirements:
  host:
    - pip
    - pbr
    - python
    - flit-core >=3.2,<4
  run:
    - python
    - pytz >=2014.4
    - requests >=2.3.0
    - six >=1.10.0

test:
  imports:
    - jenkinsapi
    - jenkinsapi.command_line
    - jenkinsapi.utils
  commands:   # [unix]
    - jenkins_invoke --help      # [unix]
    - jenkinsapi_version --help  # [unix]

about:
  home: https://github.com/salimfadhley/jenkinsapi
  license: MIT
  license_family: MIT
  license_file: license.txt
  summary: A Python API for accessing resources on a Jenkins continuous-integration server.
  doc_url: https://jenkinsapi.readthedocs.org/

extra:
  recipe-maintainers:
    - nehaljwani
