{% set name = "jenkinsapi" %}
{% set version = "0.3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: db7b2f1dbc798f9ecdbef7820546b6d651d0ef9334cded3f9919f2c64d977c66

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --no-cache-dir
  missing_dso_whitelist:   # [win]
    - '*\SHLWAPI.dll'     # [win]

requirements:
  host:
    - pip
    - pbr
    - python
  run:
    - python
    - pytz >=2014.4
    - requests >=2.3.0
    - six >=1.10.0

test:
  imports:
    - jenkinsapi
    - jenkinsapi.command_line
    - jenkinsapi.utils
    - jenkinsapi_tests
  commands:   # [unix]
    - jenkins_invoke --help      # [unix]
    - jenkinsapi_version --help  # [unix]

about:
  home: https://github.com/salimfadhley/jenkinsapi
  license: MIT
  license_family: MIT
  license_file: license.txt
  summary: A Python API for accessing resources on a Jenkins continuous-integration server.
  doc_url: https://jenkinsapi.readthedocs.org/

extra:
  recipe-maintainers:
    - nehaljwani
